### ISSUE TITLE
Próxima reunion 10/01/20

### ISSUE THREAD

**Issue by marianaiv** [crangelsmith/LHCOlympics2020_UCV#12]

**Comment by marianaiv** [comment]
Hola, @crangelsmith @camachoreina !
Los notebooks que me dijeron que revisara son estos https://github.com/lhcolympics2020/parsingscripts ? just to be sure.

P.S. No he dicho nada de la reunión porque no sé mi horario todavia.

**Comment by camachoreina** [comment]
Hola @marianaiv, 
Si, esos son los notebooks. Y la data la puedes descargar desde acá: https://zenodo.org/record/2629073#.Xbr2ai17R0t
Saludos,
Reina y @crangelsmith

**Comment by crangelsmith** [comment]
@marianaiv @camachoreina la reunion es este viernes 15h GMT, 16H CET
