### ISSUE TITLE
Próxima reunion 24/10/19

### ISSUE THREAD

**Issue by crangelsmith** [crangelsmith/LHCOlympics2020_UCV#9]

**Comment by crangelsmith** [comment]
Cuando vamos a hacer la próxima reunion? A mi me sirven los Lunes/Martes/Jueves a la hora usual, @camachoreina y tu? @marianaiv ya conoces tu horario?

**Comment by camachoreina** [comment]
Tomando en cuenta el overlap con @crangelsmith, a mi me serviría martes y jueves

**Comment by marianaiv** [comment]
No he terminado el semestre, por lo que tengo un horario medio raro de las materias que quedan, pero el jueves está bien

**Comment by marianaiv** [comment]
Qué jueves será la reunión? pensé que sería hoy.

**Comment by camachoreina** [comment]
Hola @marianaiv @crangelsmith,
@marianaiv queríamos fijar un día de la semana que funcionara para las tres. Fijamos la próxima reunión la semana que viene, Jueves 17?
Saludos,
Reina

**Comment by marianaiv** [comment]
Hola, @camachoreina, @crangelsmith. 
Justo el 17 tengo un final y no sé hasta que hora esté en la universidad. La semana que viene podría el martes 15, si les funciona.
Las inscripciones del próximo semestre son el 28, asi que por los momentos no tengo horario fijo que me funcione.

**Comment by camachoreina** [comment]
Yo no puedo el martes. Podríamos intentar el jueves de la semana siguiente.

**Comment by marianaiv** [comment]
Vale, me parece bien

**Comment by crangelsmith** [comment]
Ok, jueves 24, en el calendario.

**Comment by camachoreina** [comment]
Hola @marianaiv, ¿cómo estás?
Queríamos saber cuáles son tu disponibilidades el jueves, ¿sería posible reunirnos un poco más temprano de lo habitual? 18h00 o 18h30 CEST?

**Comment by marianaiv** [comment]
Hola, @camachoreina.
Sí, estoy disponible en ese horario. Quedamos entonces a las 18h00 CEST?

**Comment by camachoreina** [comment]
Perfecto. Hasta mañana.
